apiVersion: v1
kind: Service
metadata:
  name: c-rethinkdb
spec:
  type: ClusterIP
  selector:
    component: server-rethinkdb
  ports:
  - name: driver
    port: 28015
    targetPort: 28015
  - name: interfaz
    port: 80
    targetPort: 8080